import { TaskBundle } from "@/lib/types";

export function generateResearchMarkdown(bundle: TaskBundle): string {
  const { task, milestone, phases, totalCostUSDC } = bundle;
  const verifier = milestone.verifier_score;

  let md = `# Research Report: ${task.query}\n\n`;
  
  md += `## 📊 Executive Summary\n`;
  md += `- **Task ID:** \`${task.id}\`\n`;
  md += `- **Status:** ${task.status.toUpperCase()}\n`;
  md += `- **Created At:** ${new Date(task.created_at).toLocaleString()}\n`;
  md += `- **Total Spend:** ${totalCostUSDC} USDC / ${task.budget_usdc} USDC budget\n\n`;

  if (verifier) {
    md += `## 🛡️ Verification Results\n`;
    md += `- **Result:** ${verifier.approved ? "✅ PASS" : "❌ FAIL"}\n`;
    md += `- **Average Score:** ${verifier.averageScore.toFixed(1)} / 5.0\n`;
    if (verifier.rationale) {
      md += `> ${verifier.rationale}\n\n`;
    }
    md += `### Detailed Scores\n`;
    for (const [key, value] of Object.entries(verifier.scores)) {
      md += `- **${key.charAt(0).toUpperCase() + key.slice(1)}:** ${value}/5\n`;
    }
    md += `\n`;
  }

  md += `## 🔍 Research Phases\n\n`;
  
  for (const phase of phases) {
    md += `### Phase: ${phase.title}\n`;
    md += `**Kind:** \`${phase.kind}\`\n\n`;
    md += `${phase.content}\n\n`;
    
    if (phase.citations && phase.citations.length > 0) {
      md += `#### Citations\n`;
      for (const citation of phase.citations) {
        md += `- ${citation}\n`;
      }
      md += `\n`;
    }
    md += `---\n\n`;
  }

  md += `\n*Generated by Stipend — Autonomous Research via Trustless Work*`;

  return md;
}

export function downloadFile(filename: string, content: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function downloadReportPDF(bundle: TaskBundle) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();
  const { task, milestone, phases, totalCostUSDC } = bundle;
  const verifier = milestone.verifier_score;

  let y = 20;
  const margin = 20;
  const width = doc.internal.pageSize.getWidth();
  const contentWidth = width - margin * 2;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Research Report", margin, y);
  y += 10;
  
  doc.setFontSize(14);
  doc.setTextColor(100);
  const splitTitle = doc.splitTextToSize(task.query, contentWidth);
  doc.text(splitTitle, margin, y);
  y += (splitTitle.length * 7) + 10;

  // Header Box
  doc.setFillColor(245, 247, 250);
  doc.rect(margin, y, contentWidth, 35, 'F');
  doc.setFontSize(10);
  doc.setTextColor(0);
  y += 10;
  doc.text(`Task ID: ${task.id}`, margin + 5, y);
  y += 6;
  doc.text(`Status: ${task.status.toUpperCase()}`, margin + 5, y);
  y += 6;
  doc.text(`Created: ${new Date(task.created_at).toLocaleString()}`, margin + 5, y);
  y += 6;
  doc.text(`Total Spend: ${totalCostUSDC} USDC`, margin + 5, y);
  y += 15;

  // Verification
  if (verifier) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Verification Results", margin, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(`Outcome: ${verifier.approved ? "PASS" : "FAIL"}`, margin, y);
    y += 6;
    doc.text(`Score: ${verifier.averageScore.toFixed(1)} / 5.0`, margin, y);
    y += 8;
    
    if (verifier.rationale) {
      const rationale = doc.splitTextToSize(`Rationale: ${verifier.rationale}`, contentWidth);
      doc.text(rationale, margin, y);
      y += (rationale.length * 5) + 10;
    }
  }

  // Phases
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Research Phases", margin, y);
  y += 10;

  for (const phase of phases) {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`Phase: ${phase.title}`, margin, y);
    y += 6;
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const content = doc.splitTextToSize(phase.content, contentWidth);
    
    // Check if content fits, if not, handle page breaks
    for (let i = 0; i < content.length; i++) {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }
      doc.text(content[i], margin, y);
      y += 5;
    }
    
    y += 10;
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Stipend — Autonomous Research via Trustless Work", margin, 285);

  doc.save(`research-report-${task.id.slice(0, 8)}.pdf`);
}
